# Generated by Django 5.2.13 on 2026-04-29 14:00

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('official_name', models.CharField(max_length=128)),
                ('date_founded', models.DateTimeField(blank=True, null=True)),
                ('a_avg', models.FloatField(blank=True, null=True)),
                ('e_avg', models.FloatField(blank=True, null=True)),
                ('i_avg', models.FloatField(blank=True, null=True)),
                ('node_avg', models.FloatField(blank=True, null=True)),
                ('peri_avg', models.FloatField(blank=True, null=True)),
                ('p_avg', models.FloatField(blank=True, null=True)),
                ('coma_size', models.CharField(blank=True, max_length=128, null=True)),
                ('brightness', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comets',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Telescope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=128, unique=True)),
                ('focal_length', models.FloatField(blank=True, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'telescopes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_obs', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('coordinates', models.CharField(max_length=32)),
                ('is_public', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2026, 4, 29, 14, 0, 0, 905934))),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], max_length=16)),
                ('comet', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='observations.comet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('telescope', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='observations.telescope')),
            ],
            options={
                'db_table': 'observations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coma', models.CharField(blank=True, max_length=128, null=True)),
                ('brightness', models.IntegerField(blank=True, null=True)),
                ('axis', models.FloatField(blank=True, null=True)),
                ('exentricity', models.FloatField(blank=True, null=True)),
                ('inclination', models.FloatField(blank=True, null=True)),
                ('longtitude', models.FloatField(blank=True, null=True)),
                ('arg_perihelion', models.FloatField(blank=True, null=True)),
                ('orbital_period', models.FloatField(blank=True, null=True)),
                ('comet', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='observations.comet')),
                ('obs', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='observations.observation')),
            ],
            options={
                'db_table': 'calculations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=256)),
                ('file_name', models.CharField(max_length=256)),
                ('obs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='observations.observation')),
            ],
            options={
                'db_table': 'photos',
                'managed': True,
            },
        ),
    ]
