# Generated by Django 5.2.13 on 2026-04-29 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 29, 15, 6, 55, 351963)),
        ),
    ]
